import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'
import QuizDisplay from '../components/QuizDisplay/QuizDisplay'

import Lol from '../public/images/Lol.webp'
import Science from '../public/images/Science.webp'
import Test from '../public/images/Test.png'
import Math from '../public/images/Math.webp'

export default function Home() {
  const data = [
    {name: "Math Quiz", img: Math, difficulty: 1, path: "/quizes/0"},
    {name: "Science Quiz", img: Science, difficulty: 2, path: "/quizes/1"},
    {name: "Really Bad Jokes", img: Lol, difficulty: 0, path: "/quizes/2"}
  ] 

  return (
    <div>
      <Head>
        <title>Quiz Palace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <h1 className="mt-7 mb-7 ml-6 mr-6 text-3xl font-bold">Welcome!</h1>
        <QuizDisplay quizDisplayData={data} theme="Check out these quizes:" />
      </main>
    </div>
  )
}
